<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>de.dfki.cos.basys</groupId>
		<artifactId>pom</artifactId>
		<version>0.5.1</version>
		<relativePath/>
	</parent>

	<artifactId>processcontrol</artifactId>
	<version>0.5.2-SNAPSHOT</version>
	<packaging>pom</packaging>
	
	<name>BaSys 4.2 Process Control Services</name>
	<description>BaSys 4.2 Process Control Services</description>

	<modules>
		<module>modules/task-channel-camunda-cc</module>
		<module>modules/task-channel-mqtt-cc</module>
		<module>modules/cc-task-manager</module>
		<module>modules/mqtt-kafka-bridge</module>
		<module>modules/scale-management-service</module>
		<module>modules/wgs-management-service</module>
		
<!--		<module>modules/task-channel-camunda-wallet</module>-->
<!--        <module>modules/kafka-messaging-test</module>-->
	</modules>

	<scm>
		<url>https://github.com/dfkibasys</url>
		<connection>${gitUrl}/processcontrol.git</connection>
		<developerConnection>${gitUrl}/processcontrol.git</developerConnection>
	</scm>
</project>
